import Head from 'next/head'
import Image from 'next/image'
import { useContext } from 'react'
import { BiHorizontalCenter } from 'react-icons/bi'
import Homee from '../component/Home/Homee'
import AuthContext from '../component/Login&Signin/Auth-context'
import styles from './Home.module.css'

export default function Home() {
  const authCtx = useContext(AuthContext);
  return (
   <div className={styles.container}>
      <Head>
        <title>سكناتي</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homee/>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          موقعنا {' '}
          <span className={styles.logo}>
            <Image src="/favicon.ico" alt="Vercel Logo" width={20} height={30} />
          </span>
        </a>
      </footer>
    </div>
  )
}
